CREATE TABLE [dbo].[TournamentCashouts] (
    [TournamentCashoutId] UNIQUEIDENTIFIER NOT NULL,
    [TournamentId]        UNIQUEIDENTIFIER NOT NULL,
    [Rake]                FLOAT (53)       NOT NULL,
    [PrizePool]           FLOAT (53)       NOT NULL,
    [Food]                FLOAT (53)       NOT NULL,
    [Dotation]            FLOAT (53)       NOT NULL,
    [Floor]               FLOAT (53)       NOT NULL,
    [Comment]             VARCHAR (500)    NOT NULL,
    [CGBank]              FLOAT (53)       NOT NULL,
    [APCBank]             FLOAT (53)       NOT NULL,
    [Place_01]            FLOAT (53)       NOT NULL,
    [Place_02]            FLOAT (53)       NOT NULL,
    [Place_03]            FLOAT (53)       NOT NULL,
    [Place_04]            FLOAT (53)       NOT NULL,
    [Place_05]            FLOAT (53)       NOT NULL,
    [Place_06]            FLOAT (53)       NOT NULL,
    [Place_07]            FLOAT (53)       NOT NULL,
    [Place_08]            FLOAT (53)       NOT NULL,
    [Place_09]            FLOAT (53)       NOT NULL,
    [Place_10]            FLOAT (53)       NOT NULL,
    [BonusCash]           INT              CONSTRAINT [DF_TournamentCashouts_BonusCash] DEFAULT ((0)) NULL,
    [Dealer]              INT              NULL,
    [BonusUsed]           INT              NULL,
    [RunnerHelp]          INT              NULL,
    CONSTRAINT [PK_TournamentCashouts] PRIMARY KEY CLUSTERED ([TournamentCashoutId] ASC)
);

